#!/usr/bin/env bash
# using while script to diplay "best school" 9 times and using if to diplay hi once
x=1
while [ $x -le 10 ]
do
    echo "Best School"
    if [ $x -eq 9 ]
    then
        echo "Hi"
    fi
    x=$((x+1))
done
