#!/usr/bin/env bash
# A script to see if a file exist or not and wether its empty or not. Or if its also a normal file. 
if [ -e school ]
then
    echo "school file exists"
    if [ -s school ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f school ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
